coverage:
  notify:
    slack:
      default:
        url: secret:6lMBQpzhKN6YTQV7XPTdxMzI85++Mpa/VOfPzqxjv0XbHPDfN931islWQwT0Rwr6UAkHGGKddpfzFLsUfh/sFiNRu0sQU4R88r/9IGElQ/zesnjA0LHp7mfQasTIfx97JuRamG9bsPP7GvD9u8Nt4eTlJVjbWOksrvMT904lHk0=
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null