//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toofz.Services.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toofz.Services.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;settings&gt;
        ///  &lt;setting name=&quot;myProp1&quot;&gt;
        ///    &lt;value&gt;mySerializedValue1&lt;/value&gt;
        ///  &lt;/setting&gt;
        ///  &lt;setting name=&quot;myProp2&quot;&gt;
        ///    &lt;value&gt;mySerializedValue2&lt;/value&gt;
        ///  &lt;/setting&gt;
        ///&lt;/settings&gt;.
        /// </summary>
        internal static string BasicConfig {
            get {
                return ResourceManager.GetString("BasicConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;settings&gt;
        ///  &lt;setting name=&quot;myProp&quot;&gt;
        ///    &lt;value&gt;
        ///      &lt;XmlSerializable&gt;
        ///        &lt;Name&gt;My Serializable Type&lt;/Name&gt;
        ///        &lt;Number&gt;22&lt;/Number&gt;
        ///        &lt;Data&gt;AQIDBA==&lt;/Data&gt;
        ///      &lt;/XmlSerializable&gt;
        ///    &lt;/value&gt;
        ///  &lt;/setting&gt;
        ///&lt;/settings&gt;.
        /// </summary>
        internal static string SerializeAsXmlConfig {
            get {
                return ResourceManager.GetString("SerializeAsXmlConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;settings&gt;
        ///  &lt;setting name=&quot;myProp&quot;&gt;
        ///    &lt;value&gt;
        ///      &lt;XmlSerializable&gt;
        ///        &lt;Name&gt;My Serializable Type&lt;/Name&gt;
        ///        &lt;Number&gt;a&lt;/Number&gt;
        ///        &lt;Data&gt;AQIDBA==&lt;/Data&gt;
        ///      &lt;/XmlSerializable&gt;
        ///    &lt;/value&gt;
        ///  &lt;/setting&gt;
        ///&lt;/settings&gt;.
        /// </summary>
        internal static string SerializeAsXmlErrorConfig {
            get {
                return ResourceManager.GetString("SerializeAsXmlErrorConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;settings&gt;
        ///  &lt;setting name=&quot;myProp&quot;&gt;
        ///    &lt;value&gt;
        ///      &lt;XmlSerializable xmlns:d1p1=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; /&gt;
        ///    &lt;/value&gt;
        ///  &lt;/setting&gt;
        ///&lt;/settings&gt;.
        /// </summary>
        internal static string SerializeAsXmlIsNilConfig {
            get {
                return ResourceManager.GetString("SerializeAsXmlIsNilConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;settings&gt;
        ///  &lt;setting name=&quot;myProp&quot;&gt;
        ///    &lt;value&gt;00:00:00&lt;/value&gt;
        ///  &lt;/setting&gt;
        ///&lt;/settings&gt;.
        /// </summary>
        internal static string TimeSpanConfig {
            get {
                return ResourceManager.GetString("TimeSpanConfig", resourceCulture);
            }
        }
    }
}
