//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toofz.Services.Tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class ServiceSettingsProviderSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ServiceSettingsProviderSettings defaultInstance = ((ServiceSettingsProviderSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ServiceSettingsProviderSettings())));
        
        public static ServiceSettingsProviderSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("247080")]
        public uint AppId {
            get {
                return ((uint)(this["AppId"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForceSave {
            get {
                return ((bool)(this["ForceSave"]));
            }
            set {
                this["ForceSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:02:00")]
        public global::System.TimeSpan Duration {
            get {
                return ((global::System.TimeSpan)(this["Duration"]));
            }
            set {
                this["Duration"] = value;
            }
        }
    }
}
